### ISSUE TITLE
[binder] binding customer_group_id is zero failed

### ISSUE THREAD

**Issue by fevxie** [OCA/connector-magento#62] opened 2014-11-02 09:13 UTC
Hi, team:

```
 when I import partner.category  I find when the search result customer_group_id is 0 the job is failed. then I check the code,  I find in when I bind the magento_id with binder_id  the code has a assert sentence in the magentoerpconnect module binder file line 123:
```

   assert external_id and binding_id, (
           "external_id or binding_id missing, "
            "got: %s, %s" % (external_id, binding_id)
       )

then the external_id value is 0 and this sentence is not passed. 

I think maybe this is a bug for every object import to OE when the magento_id is zero.

**Comment by guewen** [comment] 2014-11-04 11:17
Hi,

Thanks for reporting! This is a duplicate of https://github.com/OCA/connector-magento/issues/48

There is a correction that just waits for reviews here: https://github.com/OCA/connector-magento/pull/61

**Closed as completed by guewen** 2014-11-04 11:17 UTC
