### ISSUE TITLE
Order Import Error (Odoo 8, Magento 1.9)

### ISSUE THREAD

**Issue by aignermi** [OCA/connector-magento#104] opened 2015-06-19 13:38 UTC
hi guys,

I successfully imported everything from your tutorial till the orders. All orders are failing in the import with the following error:

Traceback (most recent call last):
  File "/opt/openerp-custom/addons/connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/opt/openerp-custom/addons/connector/connector/queue/job.py", line 466, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 379, in import_record
    importer.run(magento_id, force=force)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 225, in run
    self._after_import(binding)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/sale.py", line 727, in _after_import
    self._create_payment(binding)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/sale.py", line 691, in _create_payment
    binding.openerp_id.automatic_payment(amount)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp-custom/addons/e-commerce/sale_payment_method/sale.py", line 107, in automatic_payment
    self._add_payment(journal, amount, date)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/openerp-custom/addons/e-commerce/sale_payment_method/sale.py", line 136, in _add_payment
    move_model.create(move_vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/account/account.py", line 1402, in create
    result = super(account_move, self).create(cr, uid, vals, c)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/openerp-custom/addons/connector/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4259, in _create
    result += self._columns[field].set(cr, self, id_new, field, vals[field], user, rel_context) or []
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 811, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/account/account_move_line.py", line 1282, in create
    if ('account_id' in vals) and not account_obj.read(cr, uid, [vals['account_id']], ['active'])[0]['active']:
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3386, in _read_from_database
    forbidden = missing.exists()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4860, in exists
    self._cr.execute(query, [tuple(ids)])
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: operator does not exist: integer = boolean
LINE 1: SELECT id FROM "account_account" WHERE id IN (false)
                                                  ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

Do you have an idea whats going on here?

Thanks,
Michael

**Comment by guewen** [comment] 2015-06-19 14:00
Did you configured a journal on the payment methods? Does the journal have accounts configured?

**Comment by aignermi** [comment] 2015-06-19 15:06
Hi, thanks for your quick answer! I configured a journal on the payment methods, but how do I configure accounts?

**Comment by guewen** [comment] 2015-06-22 07:09
On the journal. What is the type of your journal?

**Comment by aignermi** [comment] 2015-06-25 13:22
Hi Guewen, thanks I found the problem and fixed it, it was really wrong configuration on my side.
The problem was that I had no default debit & credit account configured.

But I have now one order that is not importing with the following error message:

Traceback (most recent call last):
  File "/opt/openerp-custom/addons/connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/opt/openerp-custom/addons/connector/connector/queue/job.py", line 466, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 379, in import_record
    importer.run(magento_id, force=force)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 197, in run
    self.magento_record = self._get_magento_data()
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/import_synchronizer.py", line 61, in _get_magento_data
    return self.backend_adapter.read(self.magento_id)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/product.py", line 245, in read
    [int(id), storeview_id, attributes, 'id'])
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/product.py", line 210, in _call
    return super(ProductProductAdapter, self)._call(method, arguments)
  File "/opt/openerp-custom/addons/connector-magento/magentoerpconnect/unit/backend_adapter.py", line 168, in _call
    result = api.call(method, arguments)
  File "/usr/local/lib/python2.7/dist-packages/magento/api.py", line 159, in call
    return self.client.call(self.session, resource_path, arguments)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 3: 'Invalid api path.'>

Is there a way to investigate this further? For example can I somehow find out which order is the problem so that I can have a look at the data that fails importing?

Thanks,
Michael

**Comment by guewen** [comment] 2015-06-25 14:08
The most important part of the traceback is missing at the bottom line, `Fault` has no description.
However, I can already say it is an error returned by Magento.

**Comment by aignermi** [comment] 2015-06-25 15:22
Hi, I know - that's why I'm asking if I can find out more about that error somewhere else. How do I proceed with this error? How do I investigate errors like that? Thanks for your help!

**Comment by guewen** [comment] 2015-06-26 05:24
You did not posted the full error, the last line is incomplete and this is where the description of the error returned by Magento is, so anybody will have difficulties to answer you.

**Comment by aignermi** [comment] 2015-06-26 08:10
![screen shot 2015-06-26 at 10 08 46 am](https://cloud.githubusercontent.com/assets/3638435/8373257/5d4b3e62-1beb-11e5-9ac5-7574c7f6c386.png)

I also don't see more (see screenshot)!

That's the reason why I'm asking where I can find out more about that error. Are there log files that I can look at?

**Comment by guewen** [comment] 2015-06-26 08:25
Yes there is more.
Look in you first traceback

```
Fault: 
```

And in the screenshot

```
Fault: <Fault 3 : 'Invalid api path.'>
```

This error indicates that the PHP module on Magento is not installed or not installed properly. Do not install the module on _Magento Connect_ but follow these instructions to install it on Magento http://odoo-magento-connector.com/guides/installation_guide.html#magento

**Comment by aignermi** [comment] 2015-06-26 08:29
I followed the instructions and I synchronized our whole store with Odoo, there is only this one job failing - so I don't think that I have a general problem here. Is there a log file on the magento side that can help me figure out what's happening here? Is there somewhere a documentation about log files?

**Comment by guewen** [comment] 2015-06-26 08:37
Probably. I'm not a Magento expert. I think you might find something by googling a bit.

**Comment by guewen** [comment] 2015-06-26 08:39
I close this issue because the original problem is solved.
BTW it would be nice if you could write the configuration error you did which led to this situation so if someone else has the same one he would find the solution.

**Closed as completed by guewen** 2015-06-26 08:39 UTC

**Comment by etech-henintsoalice** [comment] 2016-05-03 07:21
Hi guewen, i have the same problem, the partner is synchrnised from magento to odoo but for prduct, there is the same error. what's wrong. thanks to quick answer

**Comment by guewen** [comment] 2016-05-03 08:37
@alicealie That's an error on Magento, check the Magento logs.

**Comment by guewen** [comment] 2016-05-03 08:39
@alicealie it would be nice if @aignermi could answer how he solved his issue. (wrong installation of the connector plugin on Magento?)

**Comment by etech-henintsoalice** [comment] 2016-05-03 09:05
Thanks for your answer!

ok, I'll check magento logs. by the way, for the partner synchronised, when I update partner form odoo, there is no change in magento, I guess there is another configuration I must add in magento or how to do that or it is not possible?? I' ve tried to export partner from setting>connector>export partner but the form won't apply when I check it

**Comment by guewen** [comment] 2016-05-03 09:07
By default, the changes are only propagated from Magento to Odoo.
There is an additional addon to export partners https://github.com/OCA/connector-magento/tree/8.0/magentoerpconnect_export_partner but it has not been reviewed / merged : https://github.com/OCA/connector-magento/pull/91

**Comment by etech-henintsoalice** [comment] 2016-05-03 09:18
there is nothin in my magento log file.
Concerning the product, when i debug and look at the code i see that 
with magentolib.API(self.magento.location,
                                self.magento.username,
                                self.magento.password,
                                full_url=custom_url) as api: (in backend-adapter line 160 is the cause of the problem and return: access denied in log of eclipse)

Would you just give me the link to download the stable module, i download mine in https://www.odoo.com/apps/modules/8.0/magentoerpconnect/

**Comment by guewen** [comment] 2016-05-03 11:07
@alicealie use the github branches, not the apps: http://odoo-magento-connector.com/guides/installation_guide.html#odoo
You'll only have benefits by using git, such as updating to new revisions or applying patches.

**Comment by guewen** [comment] 2016-05-03 11:07
> access denied

So check the Magento web-service username and password.

**Comment by etech-henintsoalice** [comment] 2016-05-03 11:25
username and password are ok, I already print it , also for partner it works fine.
ok, thanks for your help
